#!/bin/bash

# TODO: Use the following comment format for each setting
# <AREA> (<SETTING>) [<REASON>]

# TODO: Find out what values mine should be

# Set computer name (as done via System Preferences → Sharing)
# sudo scutil --set ComputerName "0x6D746873"
# sudo scutil --set HostName "0x6D746873"
# sudo scutil --set LocalHostName "0x6D746873"
# sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "0x6D746873"